name: advanced_flutter_firebase_authentication
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # State Management
  get: ^4.6.5
  # Firebase
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_app_check: ^0.2.1+3
  # UI/UX
  flutter_screenutil: ^5.7.0
  google_fonts: ^4.0.4
  flutter_spinkit: ^5.1.0
  flutter_animate: ^4.1.1+1
  font_awesome_flutter: ^10.4.0
  flutter_svg: ^2.0.9
  # Authentication
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^5.0.8
  pinput: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
